name: Build and upload to UBDiag

on: [ push, workflow_dispatch ]

jobs:
  build:
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        flavor: [ 'dev' ]
    uses: UbiqueInnovation/actions-android/.github/workflows/android_build_ubdiag_upload.yml@v1.3.0
    with:
      projectKey: 'UB'
      app: 'Android Workshop Compose'
      flavor: '${{ matrix.flavor }}'
      concurrencyGroup: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.flavor }}
    secrets:
      ANDROID_JENKINS_PAT: ${{ secrets.ANDROID_JENKINS_PAT }}
      UB_ARTIFACTORY_URL_ANDROID: ${{ secrets.UB_ARTIFACTORY_URL_ANDROID }}
      UB_ARTIFACTORY_USERNAME: ${{ secrets.UB_ARTIFACTORY_USERNAME }}
      UB_ARTIFACTORY_PASSWORD: ${{ secrets.UB_ARTIFACTORY_PASSWORD }}
      UBIQUE_POEDITOR_API_KEY: ${{ secrets.UBIQUE_POEDITOR_API_KEY }}
      UBDIAG_UPLOAD_URL: ${{ secrets.UBDIAG_UPLOAD_URL }}
      self_hosted_cache_access_key: ${{ secrets.self_hosted_cache_access_key }}
      self_hosted_cache_secret_key: ${{ secrets.self_hosted_cache_secret_key }}
